Use sed to remove old settings in local.conf file

diff --git a/reflex-yocto-build b/reflex-yocto-build
--- a/reflex-yocto-build
+++ b/reflex-yocto-build
@@ -292,30 +292,24 @@ build_all() {
 
     source layers/poky/oe-init-build-env ./$BOARD-build-files/
 
-		# Settings for local.conf
-#		echo -e "\n[INFO] Update local.conf"
-#		sed -i /MACHINE/d conf/local.conf
-#		sed -i /UBOOT_CONFIG/d conf/local.conf
 
-    case `grep "MACHINE = \"${MACHINE}\"" "conf/local.conf" > /dev/null; echo $?` in
-        0)
-            echo ""
-            echo "local.conf is already updated."
-        ;;
-        1)
-            echo "MACHINE = \"${MACHINE}\"" >> conf/local.conf
-        #    echo 'DISTRO_FEATURES_append = " usbgadget"' >> conf/local.conf
-            echo 'DISTRO_FEATURES:append = " systemd"' >> conf/local.conf
-            echo 'VIRTUAL-RUNTIME_init_manager = "systemd"' >> conf/local.conf
-            echo ""
-            echo "Updated local.conf."
-        ;;
-        *)
-            printf "${RED}ERROR: unable to update local.conf${NC}\n\n"
-            exit 1
-        ;;
-    esac
-        
+    # Settings for local.conf
+    echo -e "${GREEN}Updating local.conf${NC}"
+
+    if [ ! -f conf/local.conf ]; then
+        printf "${RED}ERROR: unable to update local.conf${NC}\n\n"
+        exit 1
+    fi
+
+    sed -i "/MACHINE = \"${BOARD_BASE}.*\"/d" conf/local.conf
+    sed -i "/DISTRO_FEATURES:append/d" conf/local.conf
+    sed -i "/VIRTUAL-RUNTIME_init_manager/d" conf/local.conf
+
+    echo "MACHINE = \"${MACHINE}\"" >> conf/local.conf
+    echo 'DISTRO_FEATURES:append = " systemd"' >> conf/local.conf
+    echo 'VIRTUAL-RUNTIME_init_manager = "systemd"' >> conf/local.conf
+
+
     echo -e ${GREEN}
     echo "*******************************************************************"
     echo " Updating bblayers.conf...                                         "
